name: Tests
on:
  push:
    branches: *
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/poetry_setup
      - name: Test with pytest
# If we get an OpenAI API key we can remove skipped tests.
#        env:
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: poetry run pytest
        run: poetry check


